version: "3.9"

services:
    web:
        build:
            context: .
        restart: always

        env_file:
            - .env
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=./src/run.py
        networks:
        - metanet1-secrets
        volumes:
            - ./:/app
        depends_on:
            - db
    db:
        container_name: postgres
        hostname: postgres
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=${PG_DB}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        networks:
        - metanet1-secrets
        volumes:
            - db_data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - 8088:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        networks:
        - metanet1-secrets
    
    dataviz:
        image: metabase/metabase:latest
        container_name: metabase
        volumes:
        - dataviz_data:/metabase-data
        ports:
        - 3000:3000
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=${PG_DB}
            - MB_DB_PORT=${PG_PORT}
            - MB_DB_USER=${PG_USER}
            - MB_DB_PASS=${PG_PASSWORD}
            - MB_DB_HOST=postgres
            - MB_DB_FILE=/metabase-data/metabase.db
        networks:
        - metanet1-secrets
        depends_on:
        - db
networks:
  metanet1-secrets:
    driver: bridge
volumes:
    db_data:
    dataviz_data: