version: "3.9"

services:
    web:
        build:
            context: .
        restart: always

        env_file:
            - .env
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=./src/run.py
        volumes:
            - ./:/app
        depends_on:
            - db
    db:
        container_name: postgres
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=${PG_DB}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - 8088:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    
    dataviz:
        image: metabase/metabase:latest
        container_name: metabase
        volumes:
        - dataviz_data:/metabase-data
        ports:
        - 3000:3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 5432
            MB_DB_USER: ${PG_USER}
            MB_DB_PASS: ${PG_PASSWORD}
            MB_DB_HOST: ${PG_HOST}
            MB_DB_FILE: /metabase-data/metabase.db
        depends_on:
        - db
volumes:
    db_data:
    dataviz_data: